# Autogenerated by OCaml-Dockerfile scripts
FROM opensuse:42.2
MAINTAINER Anil Madhavapeddy <anil@recoil.org>
RUN zypper update -y && \
  zypper install -y -t pattern devel_C_C++ && \
  zypper update -y && \
  zypper install -y sudo gcc-c++ git unzip curl && \
  zypper update -y && \
  zypper install -y ocaml camlp4 ocaml-ocamldoc