# Autogenerated by OCaml-Dockerfile scripts
FROM justincormack/armhf-alpine:3.4
MAINTAINER Anil Madhavapeddy <anil@recoil.org>
RUN apk update && apk upgrade && \
  apk add alpine-sdk openssh bash nano ncurses-dev  && \
  cd /etc/apk/keys && curl -OL http://www.cl.cam.ac.uk/~avsm2/alpine-ocaml/x86_64/anil@recoil.org-5687cc79.rsa.pub && \
  echo http://www.cl.cam.ac.uk/~avsm2/alpine-ocaml/3.4 >> /etc/apk/repositories && \
  apk update && apk upgrade && \
  apk add ocaml camlp4