# Autogenerated by OCaml-Dockerfile scripts
FROM debian:stable
MAINTAINER Anil Madhavapeddy <anil@recoil.org>
RUN apt-get -y update && \
  apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninterative apt-get -y install sudo pkg-config git build-essential m4 software-properties-common unzip curl libx11-dev && \
  DEBIAN_FRONTEND=noninterative apt-get -y install ocaml ocaml-native-compilers camlp4-extra